services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${INFRA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${INFRA_ADMIN_PASSWORD}
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana
    networks:
      - deeplens-network

networks:
  deeplens-network:
    external: true
