// <auto-generated />
using System;
using System.Collections.Generic;
using DeepLens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeepLens.Infrastructure.Migrations
{
    [DbContext(typeof(DeepLensDbContext))]
    [Migration("20260705144420_Create_ProductShareLogs_Table")]
    partial class Create_ProductShareLogs_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<bool>("FeaturesExtracted")
                        .HasColumnType("boolean")
                        .HasColumnName("features_extracted");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("Indexed")
                        .HasColumnType("boolean")
                        .HasColumnName("indexed");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<string>("PHash")
                        .HasColumnType("text")
                        .HasColumnName("p_hash");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("QualityScore")
                        .HasColumnType("numeric")
                        .HasColumnName("quality_score");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid?>("VectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vector_id");

                    b.HasKey("Id")
                        .HasName("pk_image");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("ix_image_variant_id");

                    b.ToTable("image", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid?>("SellerListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_listing_id");

                    b.HasKey("Id")
                        .HasName("pk_price_history");

                    b.HasIndex("SellerListingId")
                        .HasDatabaseName("ix_price_history_seller_listing_id");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseSku")
                        .HasColumnType("text")
                        .HasColumnName("base_sku");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fabric")
                        .HasColumnType("text")
                        .HasColumnName("fabric");

                    b.Property<string>("StitchType")
                        .HasColumnType("text")
                        .HasColumnName("stitch_type");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UnifiedAttributes")
                        .HasColumnType("text")
                        .HasColumnName("unified_attributes");

                    b.Property<string>("WorkHeaviness")
                        .HasColumnType("text")
                        .HasColumnName("work_heaviness");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.ProductShareLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionUsed")
                        .HasColumnType("text")
                        .HasColumnName("description_used");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("SharedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shared_at");

                    b.HasKey("Id")
                        .HasName("pk_product_share_logs");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_share_logs_product_id");

                    b.ToTable("product_share_logs", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("text")
                        .HasColumnName("attributes_json");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fabric")
                        .HasColumnType("text")
                        .HasColumnName("fabric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<List<string>>("SearchKeywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("search_keywords");

                    b.Property<string>("StitchType")
                        .HasColumnType("text")
                        .HasColumnName("stitch_type");

                    b.Property<string>("VariantSku")
                        .HasColumnType("text")
                        .HasColumnName("variant_sku");

                    b.Property<string>("WorkHeaviness")
                        .HasColumnType("text")
                        .HasColumnName("work_heaviness");

                    b.HasKey("Id")
                        .HasName("pk_product_variant");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_variant_product_id");

                    b.ToTable("product_variant", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_seller");

                    b.ToTable("seller", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.SellerListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("current_price");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<DateTime>("LastPricedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_priced_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_data_json");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("ShippingInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_info");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_seller_listing");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_seller_listing_product_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_seller_listing_seller_id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("ix_seller_listing_variant_id");

                    b.ToTable("seller_listing", (string)null);
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.Image", b =>
                {
                    b.HasOne("DeepLens.Domain.Entities.Catalog.ProductVariant", "Variant")
                        .WithMany("Images")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("fk_image_product_variant_variant_id");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.PriceHistory", b =>
                {
                    b.HasOne("DeepLens.Domain.Entities.Catalog.SellerListing", null)
                        .WithMany("PriceHistory")
                        .HasForeignKey("SellerListingId")
                        .HasConstraintName("fk_price_history_seller_listing_seller_listing_id");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.Product", b =>
                {
                    b.HasOne("DeepLens.Domain.Entities.Catalog.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_product_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.ProductShareLog", b =>
                {
                    b.HasOne("DeepLens.Domain.Entities.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_share_logs_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.ProductVariant", b =>
                {
                    b.HasOne("DeepLens.Domain.Entities.Catalog.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.SellerListing", b =>
                {
                    b.HasOne("DeepLens.Domain.Entities.Catalog.Product", "Product")
                        .WithMany("Listings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seller_listing_product_product_id");

                    b.HasOne("DeepLens.Domain.Entities.Catalog.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seller_listing_seller_seller_id");

                    b.HasOne("DeepLens.Domain.Entities.Catalog.ProductVariant", "Variant")
                        .WithMany("Listings")
                        .HasForeignKey("VariantId")
                        .HasConstraintName("fk_seller_listing_product_variant_variant_id");

                    b.Navigation("Product");

                    b.Navigation("Seller");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.Product", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.ProductVariant", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("DeepLens.Domain.Entities.Catalog.SellerListing", b =>
                {
                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
